version: '3.8'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: nestuser
      DATABASE_PASSWORD: nestpass
      DATABASE_NAME: nestdb
    depends_on:
      - db
    command: npm run start:dev

volumes:
  db_data:
